//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MarBasBrokerEngineSQLite.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class BootstrapSQL {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal BootstrapSQL() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("MarBasBrokerEngineSQLite.Resources.BootstrapSQL", typeof(BootstrapSQL).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INSERT INTO mb_schema_opts (name, val) VALUES (&apos;schema.version&apos;, &apos;0.1.6&apos;);
        ///
        ////* Data for table mb_lang */
        ///INSERT INTO mb_lang (iso_code, label, label_native) VALUES (&apos;en&apos;, &apos;English&apos;, &apos;English&apos;);
        ///INSERT INTO mb_lang (iso_code, label, label_native) VALUES (&apos;en-US&apos;, &apos;English (US)&apos;, &apos;English (US)&apos;);
        ///INSERT INTO mb_lang (iso_code, label, label_native) VALUES (&apos;de&apos;, &apos;German&apos;, &apos;Deutsch&apos;);
        ///INSERT INTO mb_lang (iso_code, label, label_native) VALUES (&apos;de-DE&apos;, &apos;German (Germany)&apos;, &apos;Deutsch (Deutschland)&apos;);
        ///
        ////* D [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BasicData {
            get {
                return ResourceManager.GetString("BasicData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        internal static byte[] marbasPng {
            get {
                object obj = ResourceManager.GetObject("marbasPng", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CREATE TABLE mb_schema_opts (
        ///  name  varchar(255) NOT NULL,
        ///  val   varchar(255),
        ///  /* Keys */
        ///  CONSTRAINT mb_pk_schema_opts
        ///    PRIMARY KEY (name, val)
        ///);
        ///
        ///CREATE TABLE mb_file (
        ///  base_id    guid NOT NULL,
        ///  mime_type  varchar(255) NOT NULL DEFAULT &apos;application/octet-stream&apos;,
        ///  size       bigint NOT NULL DEFAULT -1,
        ///  content    blob,
        ///  /* Keys */
        ///  PRIMARY KEY (base_id),
        ///  /* Foreign keys */
        ///  CONSTRAINT mb_fk_file_base
        ///    FOREIGN KEY (base_id)
        ///    REFERENCES mb_grain_base(id)
        ///    O [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Scheme {
            get {
                return ResourceManager.GetString("Scheme", resourceCulture);
            }
        }
    }
}
